---
- name: Backup config of the switches
  tags: arista, vlans
  arista.eos.eos_config:
    backup: yes
    backup_options:
      dir_path: arista-backup

- name: Configure hostname
  tags: arista, basic
  eos_system:
    hostname: "{{ inventory_hostname }}"

- name: Enable non-Arista transceivers
  tags: arista, basic
  arista.eos.eos_command:
    commands:
     - service unsupported-transceivers {{ nonAristaTransceiversAreOK }}
  when: nonAristaTransceiversAreOK|length

- name: Run various commands
  tags: arista, basic
  arista.eos.eos_command:
    commands: "{{ aristaOptionalsCommands }}"

- name: Include write to startup config
  include: writeToStartupCfg.yml
  tags: arista, basic
