- name: Configure vlan trunk interfaces
  tags: arista, interfaces
  arista.eos.eos_command:
    commands:
     - interface Ethernet {{ item.number }}
     - description {{ item.description }}
     - switchport mode trunk 
     - "{{ ( item.vlans is defined and item.vlans|length) | ternary('switchport trunk allowed vlan ', 'no switchport trunk allowed vlan', '') + item.vlans | default() }}"
     - "{{ ( item.vlanNative is defined and item.vlanNative|length) | ternary('switchport trunk native vlan ', 'no switchport trunk native vlan', '') + item.vlanNative | default() }}"
     - "{{ item.shutdown | ternary('shutdown', 'no shutdown', omit) }}"
  loop: "{{ switchInterfaces }}"
  when: item.vlanMode is defined and item.vlanMode == "trunk"

- name: Configure vlan access interfaces
  tags: arista, interfaces
  arista.eos.eos_command:
    commands:
     - interface Ethernet {{ item.number }}
     - description {{ item.description }}
     - switchport mode access
     - switchport access vlan {{ item.vlans }}
     - "{{ item.shutdown | ternary('shutdown', 'no shutdown', omit) }}"
  loop: "{{ switchInterfaces }}"
  when: item.vlanMode is defined and item.vlanMode == "access"

- name: Configure non vlan interfaces
  tags: arista, interfaces
  arista.eos.eos_command:
    commands:
     - interface Ethernet {{ item.number }}
     - description {{ item.description }}
     - "{{ item.shutdown | ternary('shutdown', 'no shutdown', omit) }}"
  loop: "{{ switchInterfaces }}"
  when: item.vlanMode is not defined
  
- name: Configure interfaces with optional commands
  tags: arista, interfaces
  arista.eos.eos_command:
    commands: "{{ switchInterfacesCommands }}"
  when: switchInterfacesCommands|length

- name: Include write to startup config
  include: writeToStartupCfg.yml  
  tags: arista, interfaces

