- include: basic.yml
  tags: arista, basic

- include: users.yml
  tags: arista, users
  when: userAccounts is defined and userRoles is defined

- include: vlans.yml
  tags: arista, vlans
  when: vlans is defined and vlans|length

- include: interfaces.yml
  tags: arista, interfaces
  when: switchInterfaces|length
