- name: Add network admins 
  tags: arista, users
  set_fact:
    localNetworkAdmins: "{{ localNetworkAdmins | union(item.members) }}"
  with_items:
   - "{{ userRoles }}"
  when: item.roleName == "network-admin"

- name: Local network admins attributes
  tags: arista, users
  set_fact:
    localNetworkAdminsAttributes: "{{ localNetworkAdmins | map('extract', userAccounts ) | list }}"

- name: Configure network-admin users
  tags: arista, users
  arista.eos.eos_command:
    commands:
     - username {{ item.login }} privilege 15 role network-admin secret sha512 {{ [ secretLevel ] | map('extract', item ) | list | first }}
     - username {{ item.login }} ssh-key {{ item.sshkey }}
  loop: "{{ localNetworkAdminsAttributes }}"

- name: Include write to startup config
  include: writeToStartupCfg.yml  
  tags: arista, users

