- name: Configure VLANs for real
  tags: arista, vlans
  arista.eos.eos_command:
    commands:
     - configure
     - vlan {{ item.vlanid }}
     - name {{ item.name }}
     - no comment
     - "!! {{ item.comment }}"
  loop: "{{ vlans }}"

- name: Include write to startup config
  include: writeToStartupCfg.yml  
  tags: arista, vlans

