- name: Reset connection to switch
  meta: reset_connection

- name: Clear registered variable
  set_fact:
          diffs: ""

- name: Get startup config diffs
  arista.eos.eos_command:
    commands:
      - configure
      - show running-config diffs
  register: diffs

- name: Show startup config diffs
  debug:
    msg: "{{ diffs.stdout_lines[1] }}"
  when: diffs.stdout_lines| length > 1 and diffs.stdout_lines[1]|length>1

- name: Does the diffs looking valid to you?
  pause:
    seconds: "{{ secondsBeforeWriteCfg }}"
  when: diffs.stdout_lines| length > 1 and diffs.stdout_lines[1]|length>1

- name: Write config to startup-config
  arista.eos.eos_command:
    commands:
      - write
  when: diffs.stdout_lines| length > 1 and diffs.stdout_lines[1]|length>1

